"""Read-only catalogue of demo audio clips and renderings.

The catalogue is loaded from a JSON file (default ``configs/audio_index.json``)
that lists every dataset, every clip drawn from that dataset, and every
rendering produced for that clip (reference, CRM, Zhu, A2B).

The schema is intentionally minimal so the index can be regenerated by
``scripts/generate_audio.py`` on a fresh machine:

    {
        "datasets": [
            {
                "id": "zhu",
                "label": "Zhu (ByteDance)",
                "description": "Outdoor music recordings, 48 kHz FOA.",
                "clips": [
                    {
                        "id": "zhu_0001",
                        "source": "AmbiX-211122_2225_0001.wav",
                        "start_s": 12.0, "duration_s": 8.0,
                        "renderings": {
                            "reference": "audio/zhu/zhu_0001/reference.wav",
                            "crm":       "audio/zhu/zhu_0001/crm.wav",
                            "zhu":       "audio/zhu/zhu_0001/zhu.wav",
                            "a2b":       "audio/zhu/zhu_0001/a2b.wav"
                        }
                    }, ...
                ]
            }, ...
        ]
    }
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional


# Method identifiers used everywhere in the demo. ``reference`` is the
# ground-truth binaural recording from the dataset; the other three are
# model renderings. Display labels (Polish + English) live next to the IDs.
METHOD_LABELS: Dict[str, str] = {
    "reference": "Reference (ground truth)",
    "crm":       "Proposed CRM",
    "zhu":       "Zhu et al. 2022",
    "a2b":       "A2B (Gebru 2025)",
}
METHOD_ORDER = ("reference", "crm", "zhu", "a2b")
SYSTEMS_TO_RATE = ("crm", "zhu", "a2b")  # reference is shown but not rated


@dataclass
class Clip:
    """One audio excerpt and the path to each rendered version."""

    id: str
    source: str
    start_s: float
    duration_s: float
    renderings: Dict[str, str] = field(default_factory=dict)
    description: str = ""

    def has(self, method: str) -> bool:
        """Whether a rendering for ``method`` exists on disk."""
        path = self.renderings.get(method)
        return bool(path) and Path(path).exists()

    def path(self, method: str) -> Optional[str]:
        """Filesystem path of the rendering for ``method``, or ``None``."""
        path = self.renderings.get(method)
        if not path:
            return None
        p = Path(path)
        return str(p if p.exists() else p)


@dataclass
class Dataset:
    """A named source dataset with a list of clips."""

    id: str
    label: str
    description: str
    clips: List[Clip] = field(default_factory=list)

    def available_clips(self) -> List[Clip]:
        """Return clips that have at least the reference rendering on disk."""
        return [c for c in self.clips if c.has("reference")]


@dataclass
class Catalog:
    """Top-level container loaded from ``configs/audio_index.json``."""

    datasets: List[Dataset] = field(default_factory=list)

    def dataset(self, dataset_id: str) -> Optional[Dataset]:
        for d in self.datasets:
            if d.id == dataset_id:
                return d
        return None

    def populated_datasets(self) -> List[Dataset]:
        """Datasets that contain at least one playable clip."""
        return [d for d in self.datasets if d.available_clips()]


def load_catalog(path: str | Path) -> Catalog:
    """Load the audio catalogue from JSON.

    Missing files are kept in the catalogue so the UI can show them as
    "coming soon" rather than disappearing silently. Existence is checked
    lazily via :meth:`Clip.has`.
    """
    with open(path, "r", encoding="utf-8") as fp:
        data = json.load(fp)

    repo_root = Path(path).resolve().parent.parent  # configs/foo.json -> repo root
    datasets: List[Dataset] = []
    for ds in data.get("datasets", []):
        clips = []
        for c in ds.get("clips", []):
            # Paths in the index are repo-relative; resolve against the repo root
            # so the UI can use absolute paths to st.audio().
            renderings = {
                m: str((repo_root / p).resolve())
                for m, p in c.get("renderings", {}).items()
            }
            clips.append(Clip(
                id=c["id"],
                source=c.get("source", ""),
                start_s=float(c.get("start_s", 0.0)),
                duration_s=float(c.get("duration_s", 0.0)),
                renderings=renderings,
                description=c.get("description", ""),
            ))
        datasets.append(Dataset(
            id=ds["id"],
            label=ds.get("label", ds["id"]),
            description=ds.get("description", ""),
            clips=clips,
        ))
    return Catalog(datasets=datasets)
